# Generated by Django 5.0.4 on 2024-05-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='order_item',
        ),
        migrations.AlterModelTable(
            name='purchaseorder',
            table='purchase_order',
        ),
    ]
