# Generated by Django 5.0.4 on 2024-05-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0002_alter_orderitem_table_alter_purchaseorder_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='po_id',
            new_name='po',
        ),
    ]
