# Generated by Django 5.0.4 on 2024-05-04 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0003_rename_po_id_purchaseorder_po'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='products',
        ),
    ]
