# Generated by Django 5.0.4 on 2024-05-04 05:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0004_remove_purchaseorder_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
