# Generated by Django 5.0.4 on 2024-05-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0005_alter_purchaseorder_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
