# Generated by Django 5.0.4 on 2024-05-04 05:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0006_alter_purchaseorder_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='po_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
