# Generated by Django 5.0.4 on 2024-05-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0007_purchaseorder_po_id_alter_purchaseorder_po'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_discount',
        ),
    ]
