# Generated by Django 5.0.4 on 2024-05-04 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0008_remove_orderitem_item_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='vendor',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Warehouse.vendormodel'),
        ),
    ]
