# Generated by Django 5.0.4 on 2024-05-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0009_remove_orderitem_vendor_purchaseorder_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
