# Generated by Django 5.0.4 on 2024-05-07 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_product_display'),
        ('Warehouse', '0010_alter_orderitem_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(auto_now_add=True, verbose_name='Invoice Date')),
                ('mode_of_payment', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('UPI', 'UPI')], max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Warehouse.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='MRMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_offered', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_offered', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_offered', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouse.purchaseorder')),
            ],
        ),
    ]
