# Generated by Django 5.0.4 on 2024-05-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0012_alter_invoice_table_alter_mrmmodel_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mrmmodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='mrmmodel',
            name='purchase_order',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='MRMModel',
        ),
    ]
