# Generated by Django 5.0.4 on 2024-05-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0014_mrmmodel_mrmitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrmmodel',
            name='created',
            field=models.BooleanField(default=False, verbose_name='Is_created'),
        ),
    ]
