# Generated by Django 5.0.4 on 2024-05-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0015_mrmmodel_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mrmmodel',
            name='created',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='MRMcreated',
            field=models.BooleanField(default=False, verbose_name='Is_created'),
        ),
    ]
