# Generated by Django 5.0.4 on 2024-05-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse', '0016_remove_mrmmodel_created_purchaseorder_mrmcreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='MRMcreated',
            field=models.BooleanField(default=False),
        ),
    ]
