# Generated by Django 5.0.4 on 2024-04-15 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Costumer', '0002_alter_costumermodel_otp'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=120)),
                ('mobile', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=120)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(max_length=120)),
                ('Costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Costumer.costumermodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
