# Generated by Django 5.0.4 on 2024-04-08 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
        ('Product', '0001_initial'),
        ('Sub_Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.category')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sub_Category.subcategory')),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
    ]
