# Generated by Django 5.0.4 on 2024-04-22 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0003_alter_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='hsn_code',
        ),
    ]
