# Generated by Django 5.0.4 on 2024-04-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_product_hsn_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
