# Generated by Django 5.0.4 on 2024-04-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
