# Generated by Django 5.0.4 on 2024-04-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Costumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumermodel',
            name='otp',
            field=models.CharField(default=0, max_length=8),
        ),
    ]
